server:
  port: 8888  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver    username: root    password: QAZqaz123
    url: jdbc:mysql://127.0.0.1:3306/electronic_account?serverTimezone=UTC&characterEncoding=utf-8&useUnicode=true&tinyInt1isBit=false&allowMultiQueries=true
    initialSize: 3 
    minIdle: 3 
    maxActive: 30 
    maxWait: 15000 
    timeBetweenEvictionRunsMillis: 120000 
    minEvictableIdleTimeMillis: 300000 
    validationQuery: SELECT 'x'
    validationQueryTimeout: 1
    testWhileIdle: true 
    testOnBorrow: false 
    testOnReturn: false 
    poolPreparedStatements: false 
    maxPoolPreparedStatementPerConnectionSize: 20 
    removeAbandoned: true 
    removeAbandonedTimeoutMillis: 20000 
    logAbandoned: true 
    logDifferentThread: true 
    #filters: config,stat,wall
    connectionProperties:  druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000 
    useGlobalDataSourceStat: true 
    
    
  resources:
    static-locations: classpath:/templates      #访问静态页面

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     #mybatis的配置文件

logging:
  level:
    root: WARN
    org.mybatis: DEBUG